name: HideAndSeek
version: '1.0-SNAPSHOT'
main: de.thecoolcraft11.hideAndSeek.HideAndSeek
api-version: '1.21'
description: A minigame plugin
author: TheCoolcraft11

depend:
  - MinigameFramework
soft-depend:
  - Timer

commands:
  minigame:
    description: Game configuration and management
    usage: /minigame [subcommand] [args...]
    aliases:
      - mg

permissions:
  hideandseek.command.loadout:
    description: Allows using /mg loadout command
    default: true
  hideandseek.command.chooseblock:
    description: Allows choosing a block (hiders)
    default: op
  hideandseek.command.chooseappearance:
    description: Allows choosing appearance (hiders)
    default: op
  hideandseek.command.blockstats:
    description: Allows viewing block stats (seekers)
    default: true
  hideandseek.command.map:
    description: Allows selecting and setting maps
    default: op
  hideandseek.command.vote:
    description: Allows using /mg vote command
    default: true
