package de.thecoolcraft11.hideAndSeek.nms;

public enum NmsCapabilities {

    BLOCK_VOXEL_SHAPE,
    MOB_PATHFINDING,
    CLIENT_GAMEMODE_SPOOFING,
    NO_CLIP_MOB,
    CLIENT_LIGHTNING_PACKET,
    PROJECTILE_ENTITY_RAYCAST,
    ANTI_CHEAT_PACKET_FILTER,
    CLIENT_ENTITY_SPAWNING,
    CLIENT_CAMERA_SPOOFING,
    CLIENT_ENTITY_GLOWING,
}
